In [98]:
# import library
import pandas as pd
import numpy as np

### Question 1
What's the version of Pandas that you installed?

In [99]:
# check the version of pandas
print("The version of Pandas that installed:", pd.__version__)

The version of Pandas that installed: 2.1.0


### Question 2
How many columns are in the dataset?

In [100]:
# read the dataset
df = pd.read_csv(r"D:\Work Documents\Data Analysis\Projects\MLZoomCamp - 2023\01-Introduction\california_housing_price.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [101]:
print("The number of columns in the dataset:", df.shape[1])

The number of columns in the dataset: 10


### Question 3
Which columns in the dataset have missing values?

In [102]:
# check the null value by column
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [103]:
print("total_bedrooms column has 207 missing values")

total_bedrooms column has 207 missing values


### Question 4
How many unique values does the ocean_proximity column have?

In [104]:
# check the number of unique value by column
df.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [105]:
print("ocean_proxmity column has 5 unique values")

ocean_proxmity column has 5 unique values


### Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [106]:
# calculate the average value of the median_house_value using group_by
df.groupby('ocean_proximity')['median_house_value'].mean().round()

ocean_proximity
<1H OCEAN     240084.0
INLAND        124805.0
ISLAND        380440.0
NEAR BAY      259212.0
NEAR OCEAN    249434.0
Name: median_house_value, dtype: float64

In [107]:
print("The average value of the median_house_valkue for the houses located near the bay is 259212")

The average value of the median_house_valkue for the houses located near the bay is 259212


### Question 6

In [108]:
# calculate the average of the total_bedrooms column (missing values are included)
mean_with_nulls= df['total_bedrooms'].mean().round(3)
mean_with_nulls

537.871

In [109]:
# fill the missing values in the total_bedrooms column using the calculated mean value
df['total_bedrooms'] = df['total_bedrooms'].fillna(mean_with_nulls)
# calculate the average of the total_bedrooms column to see the difference with the prior calculation
df['total_bedrooms'].mean().round(3)

537.871

In [110]:
print("There is no difference the average value of the total_bedrooms with the missing values are included and the filled values")

There is no difference the average value of the total_bedrooms with the missing values are included and the filled values


### Question 7

In [111]:
# filter the data for the houses located in Island
df_island = df[df['ocean_proximity'] == 'ISLAND']

In [112]:
# filter the data by only selecting column house_median_age, total_rooms, and total_bedrooms
filtered_df = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [113]:
# extract the underlying numpy array
X = filtered_df.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [114]:
# createa a variable of the transpose of X
X_t = X.T
X_t

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [115]:
# compute matrix-matrix multiplication between the X_t and X
XTX = X_t.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [116]:
# compute the inverse of XTX
inv = np.linalg.inv(XTX)
inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [117]:
# create an array y
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [118]:
# multiply the inverse of XTX with X_t, then multiply the result with y
w = inv.dot(X_t).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [119]:
print("The value of the last element of w is:", w[-1])

The value of the last element of w is: 5.6992294550655656
